// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmslhycsuhuxfjejjxze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtc2xoeWNzdWh1eGZqZWpqeHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjIwMTgsImV4cCI6MjA1OTQzODAxOH0.ckc1b25UMbLTuNja4Dgyuus6FCb1kNQVETybsJLu1Zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);